# Generated by Django 5.1.6 on 2025-02-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_alter_todomodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='complected',
            field=models.BooleanField(default=False),
        ),
    ]
